### ISSUE TITLE
How to protect OpenAPI docs?

### ISSUE THREAD

**Issue by patjakubik** [cloudflare/chanfana#132]
We don't want to expose OpenAPI docs to the internet or protect them with cookies. Would that be possible?

**Comment by G4brym** [comment]
Hey @patryk-smc, the recommended way to protect it, is to use Cloudflare Access as authentication
You can learn how to set up it, in the [official docs](https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/)
